### ISSUE TITLE
Resume error in WandB.

### ISSUE THREAD

**Issue by lannguyen0910** [kaylode/theseus#33]
Forgot to create an issue in recent days.
When tested with ```resume``` argument in ```WandBCallbacks```, i encountered this error. Here's the log:
```python

[Errno 2] No such file or directory: 'main'
/content/main
2022-04-04 12:21:56 | DEBUG    | opt.py:override:78 - Overriding configuration...
2022-04-04 12:21:56 | INFO     | classification/pipeline.py:__init__:51 - {
    "global": {
        "exp_name": null,
        "exist_ok": false,
        "debug": true,
        "cfg_transform": "configs/classification/transform.yaml",
        "save_dir": "/content/main/runs",
        "device": "cuda:0",
        "use_fp16": true,
        "pretrained": null,
        "resume": null
    },
    "trainer": {
        "name": "SupervisedTrainer",
        "args": {
            "num_iterations": 2000,
            "clip_grad": 10.0,
            "evaluate_interval": 1,
            "print_interval": 20,
            "save_interval": 500
        }
    },
    "model": {
        "name": "BaseTimmModel",
        "args": {
            "name": "convnext_tiny",
            "from_pretrained": true,
            "num_classes": 180
        }
    },
    "loss": {
        "name": "FocalLoss"
    },
    "callbacks": [
        {
            "name": "LoggerCallbacks",
            "args": null
        },
        {
            "name": "CheckpointCallbacks",
            "args": {
                "best_key": "bl_acc"
            }
        },
        {
            "name": "VisualizerCallbacks",
            "args": null
        },
        {
            "name": "TensorboardCallbacks",
            "args": null
        },
        {
            "name": "WandbCallbacks",
            "args": {
                "username": "lannguyen",
                "project_name": "theseus_classification",
                "resume": true
            }
        }
    ],
    "metrics": [
        {
            "name": "Accuracy",
            "args": null
        },
        {
            "name": "BalancedAccuracyMetric",
            "args": null
        },
        {
            "name": "F1ScoreMetric",
            "args": {
                "average": "weighted"
            }
        },
        {
            "name": "ConfusionMatrix",
            "args": null
        },
        {
            "name": "ErrorCases",
            "args": null
        }
    ],
    "optimizer": {
        "name": "AdamW",
        "args": {
            "lr": 0.001,
            "weight_decay": 0.0005,
            "betas": [
                0.937,
                0.999
            ]
        }
    },
    "scheduler": {
        "name": "SchedulerWrapper",
        "args": {
            "scheduler_name": "cosine2",
            "t_initial": 7,
            "t_mul": 0.9,
            "eta_mul": 0.9,
            "eta_min": 1e-06
        }
    },
    "data": {
        "dataset": {
            "train": {
                "name": "ImageFolderDataset",
                "args": {
                    "image_dir": "/content/main/data/food-classification/train",
                    "txt_classnames": "configs/classification/classes.txt"
                }
            },
            "val": {
                "name": "ImageFolderDataset",
                "args": {
                    "image_dir": "/content/main/data/food-classification/val",
                    "txt_classnames": "configs/classification/classes.txt"
                }
            }
        },
        "dataloader": {
            "train": {
                "name": "DataLoaderWithCollator",
                "args": {
                    "batch_size": 32,
                    "drop_last": true,
                    "shuffle": false,
                    "collate_fn": {
                        "name": "MixupCutmixCollator",
                        "args": {
                            "mixup_alpha": 0.4,
                            "cutmix_alpha": 1.0,
                            "weight": [
                                0.2,
                                0.2
                            ]
                        }
                    },
                    "sampler": {
                        "name": "BalanceSampler",
                        "args": null
                    }
                }
            },
            "val": {
                "name": "DataLoaderWithCollator",
                "args": {
                    "batch_size": 32,
                    "drop_last": false,
                    "shuffle": true
                }
            }
        }
    }
}
2022-04-04 12:21:56 | DEBUG    | opt.py:load_yaml:36 - Loading config from configs/classification/transform.yaml...
2022-04-04 12:21:57 | DEBUG    | classification/datasets/folder_dataset.py:_calculate_classes_dist:71 - Calculating class distribution...
Downloading: "https://dl.fbaipublicfiles.com/convnext/convnext_tiny_1k_224_ema.pth" to /root/.cache/torch/hub/checkpoints/convnext_tiny_1k_224_ema.pth
Traceback (most recent call last):
  File "/content/main/configs/classification/train.py", line 9, in <module>
    train_pipeline = Pipeline(opts)
  File "/content/main/theseus/classification/pipeline.py", line 159, in __init__
    registry=CALLBACKS_REGISTRY
  File "/content/main/theseus/utilities/getter.py", line 15, in get_instance_recursively
    out = [get_instance_recursively(item, registry=registry, **kwargs) for item in config]
  File "/content/main/theseus/utilities/getter.py", line 15, in <listcomp>
    out = [get_instance_recursively(item, registry=registry, **kwargs) for item in config]
  File "/content/main/theseus/utilities/getter.py", line 26, in get_instance_recursively
    return registry.get(config['name'])(**args, **kwargs)
TypeError: type object got multiple values for keyword argument 'resume'
```

I guess because of the ```resume``` arg is both repeated in ```global``` and ```WandBCallbacks```. Maybe it also happens with ```Tensorboard```.

**Comment by kaylode** [comment]
I will look into this soon. Crazily busy at the moment.

**Comment by kaylode** [comment]
This is not a bug, this happended because WandbCallbacks were used in the wrong way

In `pipeline.yaml`
```python
"name": "WandbCallbacks",
"args": {
    "username": "lannguyen",
    "project_name": "theseus_classification",
    "resume": true # <----- you didnt have to specify this
}
```

The repo havent been fully-well documented therefore it will be confusing sometimes.
